# Generated by Django 2.2.10 on 2021-06-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_questionnaire', '0004_remove_questionmodel_type_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='type_question',
            field=models.CharField(choices=[('text', 'ответ текстом'), ('choice_one', 'ответ с выбором одного варианта'), ('choice_many', 'ответ с выбором нескольких вариантов')], default=1, max_length=11, verbose_name='тип опроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_questionnaire.PollModel', verbose_name='Опрос'),
        ),
    ]
