# Generated by Django 2.2.10 on 2021-06-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_questionnaire', '0005_auto_20210618_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionQuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_questionnaire.QuestionModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='pollmodel',
            name='choice_answer',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='answerText',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answermodel',
            name='questionText',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answermodel',
            unique_together={('question', 'answered_by')},
        ),
        migrations.DeleteModel(
            name='OneQuestion',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='poll',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='option_question',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_model', to='app_questionnaire.OptionQuestionModel', verbose_name='варианты ответов'),
        ),
    ]
