# Generated by Django 2.2.10 on 2021-06-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_questionnaire', '0006_auto_20210622_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='many_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_questionnaire.OptionQuestionModel', verbose_name='выбор одного'),
        ),
    ]
