# Generated by Django 2.2.10 on 2021-06-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questionnaire', '0008_auto_20210622_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionquestionmodel',
            name='question',
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='answerText',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='текст ответа'),
        ),
    ]
