# Generated by Django 2.2.10 on 2021-06-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_questionnaire', '0009_auto_20210622_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_poll', to='app_questionnaire.QuestionModel', verbose_name='Опрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='option_question',
            field=models.ManyToManyField(blank=True, related_name='question_model', to='app_questionnaire.OptionQuestionModel', verbose_name='варианты ответов'),
        ),
    ]
