# Generated by Django 3.2.4 on 2021-06-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_questionnaire', '0010_auto_20210622_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='many_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_questionnaire.optionquestionmodel', verbose_name='выбор одного'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='option_question',
            field=models.ManyToManyField(related_name='question_model', to='app_questionnaire.OptionQuestionModel', verbose_name='варианты ответов'),
        ),
    ]
